// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Github_hyfree_SpamClassificationML.Model
{
    public class ModelInput
    {
        [ColumnName("lable"), LoadColumn(0)]
        public bool Lable { get; set; }


        [ColumnName("value"), LoadColumn(1)]
        public string Value { get; set; }


    }
}
